name: ditto
description: The common API for clipboard platform plugins
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  ditto_interface:
    path: ../ditto_interface
  ditto_macos:
    path: ../ditto_macos
  ditto_windows:
    path: ../ditto_windows

  flutter:
    sdk: flutter

dev_dependencies:
  rows_lint: 0.1.1

flutter:
  plugin:
    platforms:
      windows:
        default_package: ditto_windows
      macos:
        default_package: ditto_macos
