name: clipboard
description: A plugin to work with clipboard.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  clipboard_api:
    path: ./packages/clipboard_api
  clipboard_windows:
    path: ./packages/clipboard_windows
  clipboard_macos:
    path: ./packages/clipboard_macos
  flutter:
    sdk: flutter

dev_dependencies:
  rows_lint: 0.1.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        default_package: clipboard_windows
      macos:
        default_package: clipboard_macos
