name: clipboard_macos
description: Clipboard implementation for macOS
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  clipboard_api:
    path: ../clipboard_api

  flutter:
    sdk: flutter

dev_dependencies:
  rows_lint: 0.1.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: clipboard
    platforms:
      macos:
        dartPluginClass: MacosClipboard
        pluginClass: ClipboardMacosPlugin
