name: clipboard_api
description: The common API for clipboard platform plugins
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dart_lint_template:
    path: ../../../dart_lint_template
